#!/usr/bin/python3

#单个变量赋值
a='1'
b=2
c=3.0
print(a)
print(b)
print(c)

#多个变量赋值
a1,b1,c1=1,"2","row3"
print(a1)
print(b1)
print(c1)

#复数
complex=4+3j
print(type(complex))
#type()不会认为子类是一种父类类型。
#isinstance()会认为子类是一种父类类型。
print(isinstance(complex,int))

#list
list = ['abcd',2.23,'runoob',70.2]
tinylist = [123, 'runoob']

print(list)#输出完整列表
print(list[0])#输出列表第一个元素
print(list[1:3])#输出第二个开始到第三个元素
print(list[2:])#输出第三个之后的所有
print(tinylist * 2)#输出两次
print(list + tinylist) #连接列表

#元组
tuple = ('abcd', 786, 2.23, 'runoob', 70.2)
tinytuple = (123, 'runoob')
tuple1 = (20)#元组只有一个元素，后面需要加逗号

print(tuple1)             # 输出完整元组
print(tuple[0])          # 输出元组的第一个元素
print(tuple[1:3])        # 输出从第二个元素开始到第三个元素
print(tuple[2:])         # 输出从第三个元素开始的所有元素
print(tinytuple * 2)     # 输出两次元组
print(tuple + tinytuple) # 连接元组

#字典
dict = {}
dict['one'] = "1 - 菜鸟教程"
dict[2]     = "2 - 菜鸟工具"

tinydict = {'name': 'runoob','code':1, 'site': 'www.runoob.com'}

print(dict['one'])       # 输出键为 'one' 的值
print(dict[2])           # 输出键为 2 的值
print(tinydict)          # 输出完整的字典
print(tinydict.keys())   # 输出所有键
print(tinydict.values()) # 输出所有值